# IMPORTANT: Please note the LOCAL IP, TOKEN_ID and REG_NO need to be replaced with your own values for this to work

solax_cloud_api: https://www.solaxcloud.com/proxyApp/proxy/api/getRealtimeInfo.do?tokenId=TOKEN_ID&sn=REG_NO

solax_local_ip: http://192.x.x.x/ # IP of solax module

solax_local_realtime_payload:                       "optType=ReadRealTimeData&pwd=REG_NO"

solax_local_settings_payload:                       "optType=ReadSetData&pwd=REG_NO"

solax_local_set_inverter_mode:                      'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":28,"val":"{{ value }}"}]}'

solax_local_set_battery_min_soc_payload:            'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":29,"val":"{{ level }}"}]}'

solax_local_set_battery_grid_charge_level_payload:  'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":31,"val":"{{ level }}"}]}'

solax_local_set_manual_mode_behaviour:              'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":36,"val":"{{ value }}"}]}'

solax_local_set_battery_forced_charge_start:        'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":37,"val":"{{ value }}"}]}'
solax_local_set_battery_forced_charge_stop:         'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":38,"val":"{{ value }}"}]}'

solax_local_set_period2_enable_payload:             'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":41,"val":"{{ enabled }}"}]}'

solax_local_set_battery_forced_charge_start2:       'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":42,"val":"{{ value }}"}]}'
solax_local_set_battery_forced_charge_stop2:        'optType=setReg&pwd=REG_NO&data={"num":1,"Data":[{"reg":43,"val":"{{ value }}"}]}'
